### ISSUE TITLE
e2e Feature Request: add timestamp

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-end-to-end-tests#104]
### Is your feature request related to a problem?

I was looking into an e2e tests failure log, trying to understand if I was running into a timeout issue.

Unfortunately all the output produced by the e2e tests doesn't have a timestamp associated. That makes impossible to understand how much time passed between two log statements.

### Solution you'd like

All the output of the e2e tests should have a timestamp: date and time

**Comment by fabriziosestito** [comment]
Maybe this is a noop, see https://github.com/debug-js/debug/issues/565#issuecomment-1335344834

![image](https://github.com/kubewarden/kubewarden-end-to-end-tests/assets/828651/bedeedc3-c7a1-4a6d-99e2-92e61a5b655e)

**Comment by flavio** [comment]
Thanks for the tip, we can close this issue if you want @kravciak

**Comment by kravciak** [comment]
I found `-T  Add timing information to tests` bats option. I will test what it does (to have something on local runs too).

**Comment by kravciak** [comment]
I created https://github.com/kubewarden/kubewarden-end-to-end-tests/pull/105.
Timing information in bats are quite limited, github action timestamps are much better.

For example here only adds 43214 - test duration in milliseconds..
```
monitor-mode-tests.bats
 ✓ [Monitor mode end-to-end tests] Install ClusterAdmissionPolicy in monitor mode [43214 (timeout: 5m)]
   clusteradmissionpolicy.policies.kubewarden.io/privileged-pods created
   clusteradmissionpolicy.policies.kubewarden.io/privileged-pods condition met
   deployment "policy-server-default" successfully rolled out
   clusteradmissionpolicy.policies.kubewarden.io/privileged-pods condition met
```
