### ISSUE TITLE
Tracker issue: remove Jaeger workaround when not needed

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-end-to-end-tests#111]
This is a tracker issue to remove the Jaeger workaround added in https://github.com/kubewarden/kubewarden-end-to-end-tests/pull/109. This workaround adds RBAC for listing the ingressclasses, see https://github.com/jaegertracing/helm-charts/issues/549.

### Acceptance criteria

Once the workaround is not needed, it is removed and jaeger tracing works in the tests.

**Comment by kravciak** [comment]
Workaround removed: https://github.com/kubewarden/kubewarden-end-to-end-tests/pull/115
