### ISSUE TITLE
Feature Request: Sigstore verification tests

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-end-to-end-tests#19]
### Solution you'd like

Add tests for:

configure helm chart with verification enabled for kubewarden policies, but misconfigured
deploy policies, seeing that they are rejected
upgrade helm chart with correct verification configuration
configure helm chart with verification enabled for kubewarden policies
deploy policies, seeing that they are verified and instantiated

**Comment by jvanz** [comment]
Waiting for the controller release to continue this.

**Comment by jvanz** [comment]
Working to merge this. The controller fixed the issue that was blocking this.
