### ISSUE TITLE
Set up a Github runner

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-end-to-end-tests#42]
We use to have a self-hosted github runner to run our e2e tests in the past. But due some issue we lost the instance and we rely on the VM created by @kravciak which could die anytime as well. Therefore, we need to create a new runner in GCP for our CI jobs.

**Comment by aktech** [comment]
By the way, if you want a no-maintenance method to achieve that, you can use [cirun.io](https://cirun.io) for the same.
