### ISSUE TITLE
E2E tests timeout when installing kubewarden-controller chart

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-end-to-end-tests#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems that E2E tests fail to install `kubewarden-controller`, and time out in the jobs.
See:
https://github.com/kubewarden/helm-charts/pull/220
https://github.com/kubewarden/helm-charts/actions/runs/4697628661/jobs/8328923335

Tests for that PR (1.6.0-rc6) were performed manually, and passed without a problem when installing kubewarden-controller.

Charts under test:
```
kubewarden-controller-1.5.0-rc6  v1.6.0-rc6
kubewarden-crds-1.3.0-rc6           v1.6.0-rc6
kubewarden-defaults-1.6.0-rc6    v1.6.0-rc6
```

### Expected Behavior

E2E install kubewarden-controller successfully and don't time out.

**Comment by kravciak** [comment]
Do we plan to make some changes to helm charts soon? This PR passed CI, but I thought it would be good to double check before closing.
Or you can reopen on new failures, what do you prefer?

**Comment by kravciak** [comment]
Closing, timeout problem is fixed.
