### ISSUE TITLE
E2E fail because of opentelemetry chart changes

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-end-to-end-tests#98]
E2E tests failed as it seems that opentelemetry values.yaml needs manager.collectorImage.repository set:
https://github.com/kubewarden/helm-charts/actions/runs/8871318080/job/24354123203#step:6:38

See https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/UPGRADING.md

## Acceptance criteria

- [x] Amend E2E tests to work for latest opentelemetry chart.
  https://github.com/kubewarden/kubewarden-end-to-end-tests/pull/99
- [x] Amend https://docs.kubewarden.io/howtos/telemetry/opentelemetry-qs
  https://github.com/kubewarden/docs/pull/398

**Comment by kravciak** [comment]
E2E tests fix: https://github.com/kubewarden/kubewarden-end-to-end-tests/pull/99. 
Just want to double check we should use `collector-contrib`, not `collector-k8s` before merging.

**Comment by kravciak** [comment]
PRs created, closing.
